export const COLLECTION_TITLE_MIN_LENGTH = 1;

export const COLLECTION_TITLE_MAX_LENGTH = 100;

export const COLLECTION_DESCRIPTION_MIN_LENGTH = 1;

export const COLLECTION_DESCRIPTION_MAX_LENGTH = 1000;
